spring:
  datasource:
    username: KenA104
    password: revlearning
    url: jdbc:oracle:thin:@revdatabaselearning.cdaduat705rc.us-east-2.rds.amazonaws.com:1521:ORCL

    jpa:
      database-platfrom: org.hibernate.dialect.Oracle10gDialect



